{{- $clustername := .Values.cluster.name }}
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
{{- if .Values.cluster.labels }}
  labels:
{{ toYaml .Values.cluster.labels | indent 4 }}
{{- end }}
  {{- if .Values.cluster.annotations }}
  annotations:
{{ toYaml .Values.cluster.annotations | indent 4 }}
  {{- end }}
  name: {{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  {{- if .Values.cloudCredentialSecretName }}
  cloudCredentialSecretName: {{ .Values.cloudCredentialSecretName }}
  {{- end }}
  kubernetesVersion: {{ .Values.kubernetesVersion }}
  localClusterAuthEndpoint:
    enabled: true
  rkeConfig:
    machinePools:
    {{- range $index, $nodepool := .Values.nodepools }}
    - name: {{ $clustername }}-{{ $nodepool.name }}
      {{- if $nodepool.etcd }}
      etcdRole: true
      {{- end }}
      {{- if $nodepool.controlplane }}
      controlPlaneRole: true
      {{- end }}
      {{- if $nodepool.worker }}
      workerRole: true
      {{- end }}
      quantity: {{ $nodepool.quantity }}
      {{- if $nodepool.autoscale }}
      machineDeploymentAnnotations:
        cluster.provisioning.cattle.io/autoscaler-max-size: '100'
        cluster.provisioning.cattle.io/autoscaler-min-size: '1'
      {{- end }}
      {{- if $nodepool.labels }}
      labels:
{{ toYaml $nodepool.labels | indent 8 }}
      {{- end }}
      {{- if $nodepool.taints }}
      taints:
{{ toYaml $nodepool.taints | indent 8 }}
      {{- end }}
      machineConfigRef:
        kind: MakecloudConfig
        name: {{ $nodepool.name }}
    {{- end }}
    machineGlobalConfig:
      cluster-cidr: {{ .Values.cluster.clusterCidr }}
      service-cidr: {{ .Values.cluster.serviceCidr }}
      cluster-domain: {{ .Values.cluster.clusterDomain }}
      cni: {{ .Values.cni }}
    additionalManifest:
{{ toYaml .Values.additionalManifest | indent 6 }}
    machineSelectorConfig:
      - config:
          embedded-registry: true
          supervisor-metrics: true
    registries:
{{ toYaml .Values.registries | indent 6 }}
    upgradeStrategy:
{{- $upgradeStrategy := deepCopy (.Values.upgradeStrategy | default dict) }}
{{- if and (hasKey $upgradeStrategy "controlPlaneDrainOptions") (hasKey $upgradeStrategy.controlPlaneDrainOptions "ignoreErrors") (eq $upgradeStrategy.controlPlaneDrainOptions.ignoreErrors false) }}
{{- $_ := unset $upgradeStrategy.controlPlaneDrainOptions "ignoreErrors" }}
{{- end }}
{{- if and (hasKey $upgradeStrategy "workerDrainOptions") (hasKey $upgradeStrategy.workerDrainOptions "ignoreErrors") (eq $upgradeStrategy.workerDrainOptions.ignoreErrors false) }}
{{- $_ := unset $upgradeStrategy.workerDrainOptions "ignoreErrors" }}
{{- end }}
{{ toYaml $upgradeStrategy | indent 6 }}
    etcd:
{{- $etcd := deepCopy (.Values.etcd | default dict) }}
{{- if and (hasKey $etcd "disableSnapshots") (eq $etcd.disableSnapshots false) }}
{{- $_ := unset $etcd "disableSnapshots" }}
{{- end }}
{{ toYaml $etcd | indent 6 }}
